// Generates supabase/migrations/0002_seed.sql from src/data/venues.json,
// keeping the bundled fallback data and the database in lockstep.
// Usage: node scripts/generate-seed.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const venues = JSON.parse(
  readFileSync(join(root, "src", "data", "venues.json"), "utf8")
);

const q = (v) => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") return String(v);
  return `'${String(v).replace(/'/g, "''")}'`;
};
const arr = (a) => `'{${a.map((s) => `"${s}"`).join(",")}}'`;
const jsonb = (v) => `${q(JSON.stringify(v))}::jsonb`;

let sql = `-- Generated by scripts/generate-seed.mjs — do not edit by hand.
-- Seed data: curated private-dining venues for the three challenge markets.

truncate public.venues cascade;

`;

for (const v of venues) {
  sql += `insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  ${q(v.id)}, ${q(v.name)}, ${q(v.address)}, ${q(v.city)}, ${q(v.region)},
  ${v.lat}, ${v.lng}, ${q(v.cuisine)}, ${q(v.description)},
  ${q(v.rating)}, ${q(v.review_count)}, ${q(v.price_tier)}, ${q(v.min_spend)},
  ${q(v.price_trust)}, ${q(v.trust_label)}, ${arr(v.dietary)}, ${arr(v.event_styles)},
  ${q(v.image_url)}, ${q(v.menu_url)}, ${q(v.menu_image_url)}, ${jsonb(v.menu_highlights)},
  ${q(v.contact.name)}, ${q(v.contact.email)}, ${q(v.contact.phone)}
);
`;
  for (const r of v.rooms) {
    sql += `insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values (${q(v.id)}, ${q(r.name)}, ${r.seated}, ${r.standing}, ${q(r.notes)});
`;
  }
  sql += "\n";
}

const out = join(root, "supabase", "migrations", "0002_seed.sql");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, sql);
console.log(`Wrote ${out} (${venues.length} venues)`);
