-- Generated by scripts/generate-seed.mjs — do not edit by hand.
-- Seed data: curated private-dining venues for the three challenge markets.

truncate public.venues cascade;

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'carmines-times-square', 'Carmine''s Italian Restaurant', '200 W 44th St, New York, NY 10036', 'New York', 'nyc',
  40.7576, -73.987, 'Italian', 'Family-style Southern Italian institution one block off Times Square, built for big tables and bigger platters.',
  4.2, 5182, 2, 3500,
  'verified', 'verified', '{"vegetarian","vegan","gluten_free","nut_allergy"}', '{"seated","reception"}',
  'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=60', 'https://www.carminesnyc.com/', 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=900&q=60', '[{"dish":"Chicken Parmigiana (family style)","price":"$48"},{"dish":"Linguine with White Clam Sauce","price":"$42"},{"dish":"Veal Marsala","price":"$56"},{"dish":"Titanic Ice Cream Sundae","price":"$28"}]'::jsonb,
  'Group Sales Office', 'groupsales@carminesnyc.com', '(212) 221-3800'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('carmines-times-square', 'Palace Room', 80, 100, 'Second-floor room with full AV');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('carmines-times-square', 'Broadway Room', 40, 60, 'Semi-private curtained alcove');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'gallaghers-steakhouse', 'Gallaghers Steakhouse', '228 W 52nd St, New York, NY 10019', 'New York', 'nyc',
  40.7634, -73.9837, 'Steakhouse', '1927 Broadway steakhouse with a glass-walled dry-aging room and clubby wood-panelled private rooms.',
  4.4, 2451, 4, 6000,
  'verified', 'verified', '{"vegetarian","gluten_free","nut_allergy"}', '{"seated","reception"}',
  'https://images.unsplash.com/photo-1544025162-d76694265947?w=900&q=60', 'https://gallaghersnysteakhouse.com/', 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=900&q=60', '[{"dish":"Dry-Aged NY Strip","price":"$72"},{"dish":"Jumbo Lump Crab Cake","price":"$32"},{"dish":"Creamed Spinach","price":"$16"},{"dish":"NY Cheesecake","price":"$16"}]'::jsonb,
  'Private Events Team', 'events@gallaghersnysteakhouse.com', '(212) 586-5000'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('gallaghers-steakhouse', 'The 52nd Street Room', 80, 100, 'Full buyout of front dining room');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('gallaghers-steakhouse', 'Wine Room', 24, 30, 'Surrounded by the cellar collection');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'becco-nyc', 'Becco', '355 W 46th St, New York, NY 10036', 'New York', 'nyc',
  40.7605, -73.9899, 'Italian', 'Lidia Bastianich''s Restaurant Row trattoria, famous for the unlimited fresh pasta sinfonia.',
  4.3, 3210, 2, null,
  'likely', 'verified', '{"vegetarian","gluten_free"}', '{"seated"}',
  'https://images.unsplash.com/photo-1481931098730-318b6f776db0?w=900&q=60', 'https://www.becco-nyc.com/', null, '[{"dish":"Sinfonia di Paste (unlimited trio)","price":"$36"},{"dish":"Osso Buco alla Milanese","price":"$49"},{"dish":"Grilled Swordfish","price":"$38"}]'::jsonb,
  'Private Dining Coordinator', null, '(212) 397-7597'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('becco-nyc', 'Terrazza', 30, 40, 'Second-floor private room');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('becco-nyc', 'Vino Room', 16, 0, 'Intimate wine-lined room');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'sardis-nyc', 'Sardi''s', '234 W 44th St, New York, NY 10036', 'New York', 'nyc',
  40.7579, -73.9875, 'American', 'The caricature-covered Broadway landmark; upstairs banquet rooms host opening-night parties.',
  4, 1875, 3, null,
  'unverified', 'likely', '{"vegetarian","gluten_free"}', '{"seated","reception"}',
  'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=900&q=60', 'https://www.sardis.com/', null, '[{"dish":"Shrimp Sardi","price":"$34"},{"dish":"Steak Tartare (prepared tableside)","price":"$39"},{"dish":"Roast Long Island Duckling","price":"$42"}]'::jsonb,
  'Banquet Office', 'banquets@sardis.com', '(212) 221-8440'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('sardis-nyc', 'Belasco Room', 65, 80, 'Third floor, windows on 44th St');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('sardis-nyc', 'Eugenia Room', 120, 150, 'Full-floor banquet space');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'del-friscos-nyc', 'Del Frisco''s Double Eagle Steakhouse', '1221 Avenue of the Americas, New York, NY 10020', 'New York', 'nyc',
  40.7597, -73.9818, 'Steakhouse', 'Three-story glass flagship across from Radio City with a dedicated private-dining floor.',
  4.3, 2988, 4, 8000,
  'verified', 'verified', '{"vegetarian","gluten_free","nut_allergy"}', '{"seated","reception"}',
  'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=900&q=60', 'https://delfriscos.com/', 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=900&q=60', '[{"dish":"45-Day Dry-Aged Ribeye","price":"$78"},{"dish":"Cheesesteak Eggrolls","price":"$24"},{"dish":"Lobster Mac & Cheese","price":"$29"}]'::jsonb,
  'Private Events Director', 'nycevents@delfriscos.com', '(212) 575-5129'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('del-friscos-nyc', 'Eagle Room', 80, 100, 'Largest room, full AV and bar');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('del-friscos-nyc', 'Skyline Room', 40, 60, 'Views over Sixth Avenue');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('del-friscos-nyc', 'Board Room', 16, 0, 'Executive dinner setting');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'bond45-nyc', 'Bond 45', '221 W 46th St, New York, NY 10036', 'New York', 'nyc',
  40.7593, -73.9861, 'Italian', 'Sprawling Theater District Italian kitchen and bar inside the old Bond clothing store sign.',
  4.2, 2103, 3, null,
  'unverified', 'likely', '{"vegetarian","gluten_free"}', '{"seated","reception"}',
  'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=900&q=60', 'https://www.bond45.com/', null, '[{"dish":"Mozzarella Tasting","price":"$28"},{"dish":"Tagliatelle Bolognese","price":"$34"},{"dish":"Bistecca Fiorentina for two","price":"$130"}]'::jsonb,
  'Events Office', null, '(212) 869-4545'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('bond45-nyc', 'Mezzanine', 90, 140, 'Overlooks the main dining room');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('bond45-nyc', 'Sofia Room', 45, 65, 'Private with dedicated bar');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'tonys-di-napoli', 'Tony''s Di Napoli', '147 W 43rd St, New York, NY 10036', 'New York', 'nyc',
  40.7557, -73.9848, 'Italian', 'Family-style red-sauce favorite steps from Times Square that routinely seats groups in the hundreds.',
  4.3, 4056, 2, 2500,
  'verified', 'verified', '{"vegetarian","vegan","gluten_free","nut_allergy"}', '{"seated","reception"}',
  'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=900&q=60', 'https://www.tonysnyc.com/', 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=900&q=60', '[{"dish":"Penne alla Vodka (family style)","price":"$38"},{"dish":"Chicken Scarpariello","price":"$44"},{"dish":"Zeppole","price":"$18"}]'::jsonb,
  'Group Dining Team', 'events@tonysnyc.com', '(212) 221-0100'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('tonys-di-napoli', 'Times Square Room', 150, 200, 'Dedicated private floor');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('tonys-di-napoli', 'Garden Room', 60, 80, 'Skylit rear room');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'havana-central', 'Havana Central Times Square', '151 W 46th St, New York, NY 10036', 'New York', 'nyc',
  40.7589, -73.984, 'Cuban', 'Live salsa bands, mojito pitchers, and one of the biggest event floors in the Theater District.',
  4, 3390, 2, 3000,
  'verified', 'verified', '{"vegetarian","gluten_free"}', '{"seated","reception"}',
  'https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?w=900&q=60', 'https://www.havanacentral.com/', null, '[{"dish":"Ropa Vieja","price":"$29"},{"dish":"Lechón Asado","price":"$31"},{"dish":"Mojito Pitchers","price":"$58"}]'::jsonb,
  'Events & Catering', 'events@havanacentral.com', '(212) 398-7440'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('havana-central', 'Havana Ballroom', 180, 300, 'Full second floor with stage');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('havana-central', 'Salsa Lounge', 60, 100, 'Semi-private with bar');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'ruths-chris-nyc', 'Ruth''s Chris Steak House', '148 W 51st St, New York, NY 10019', 'New York', 'nyc',
  40.7611, -73.9822, 'Steakhouse', 'Sizzling-butter steaks in a polished midtown room with a suite of configurable private spaces.',
  4.2, 1730, 4, 5000,
  'likely', 'verified', '{"vegetarian","gluten_free","nut_allergy"}', '{"seated"}',
  'https://images.unsplash.com/photo-1560624052-449f5ddf0c31?w=900&q=60', 'https://www.ruthschris.com/', null, '[{"dish":"Filet, 8oz — sizzling butter","price":"$62"},{"dish":"Seared Ahi Tuna","price":"$26"},{"dish":"Potatoes au Gratin","price":"$15"}]'::jsonb,
  'Sales Manager', null, '(212) 245-9600'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('ruths-chris-nyc', 'Broadway Room', 80, 0, 'Combines two rooms');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('ruths-chris-nyc', 'Gallery', 30, 0, 'Off the main dining room');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('ruths-chris-nyc', 'Study', 12, 0, 'Board-style table');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'le-bernardin', 'Le Bernardin', '155 W 51st St, New York, NY 10019', 'New York', 'nyc',
  40.7616, -73.9818, 'French', 'Eric Ripert''s three-Michelin-star seafood temple; Le Bernardin Privé is its serene private-event floor.',
  4.6, 2870, 4, 15000,
  'verified', 'verified', '{"vegetarian","gluten_free","nut_allergy","kosher"}', '{"seated","reception"}',
  'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=900&q=60', 'https://www.le-bernardin.com/', null, '[{"dish":"Chef''s Tasting Menu","price":"$298"},{"dish":"Poached Lobster","price":"—"},{"dish":"Barely-Cooked Salmon","price":"—"}]'::jsonb,
  'Privé Events Team', 'prive@le-bernardin.com', '(212) 554-1515'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('le-bernardin', 'Salon', 70, 80, 'Full Privé floor');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('le-bernardin', 'Screening Room', 20, 30, 'Intimate with projection wall');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'stk-midtown', 'STK Steakhouse Midtown', '1114 Avenue of the Americas, New York, NY 10036', 'New York', 'nyc',
  40.7553, -73.984, 'American', 'DJ-driven modern steakhouse with a rooftop that flips into reception mode for big corporate crowds.',
  4, 2245, 3, null,
  'unverified', 'likely', '{"vegetarian","gluten_free"}', '{"reception","seated"}',
  'https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?w=900&q=60', 'https://stksteakhouse.com/', null, '[{"dish":"Wagyu Beef Sliders","price":"$26"},{"dish":"Tuna Tartare","price":"$28"},{"dish":"Dry-Aged Bone-In Strip","price":"$84"}]'::jsonb,
  'Events Sales', null, '(646) 624-2455'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('stk-midtown', 'Rooftop', 120, 200, 'Seasonal, covered options');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('stk-midtown', 'Vault Room', 40, 60, 'Lower-level private room');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'toloache-50', 'Toloache', '251 W 50th St, New York, NY 10019', 'New York', 'nyc',
  40.762, -73.985, 'Mexican', 'Bi-level contemporary Mexican bistro with a mezcal library and a snug mezzanine for groups.',
  4.3, 1922, 2, null,
  'unverified', 'unverified', '{"vegetarian","vegan","gluten_free"}', '{"seated"}',
  'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=900&q=60', 'https://www.toloachenyc.com/', null, '[{"dish":"Taquiza Tasting (grasshopper optional)","price":"$34"},{"dish":"Enchiladas de Mole Negro","price":"$29"},{"dish":"Tableside Guacamole","price":"$19"}]'::jsonb,
  'Reservations', null, '(212) 581-1818'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('toloache-50', 'Mezzanine', 30, 40, 'Semi-private balcony level');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'tang-pavilion', 'Tang Pavilion', '65 W 55th St, New York, NY 10019', 'New York', 'nyc',
  40.7633, -73.9769, 'Chinese', 'White-tablecloth Shanghainese standby near City Center, quietly experienced with banquet parties.',
  4.1, 987, 2, null,
  'unverified', 'unverified', '{"vegetarian","vegan","gluten_free"}', '{"seated"}',
  'https://images.unsplash.com/photo-1526318896980-cf78c088247c?w=900&q=60', 'https://www.tangpavilionnyc.com/', null, '[{"dish":"Peking Duck (whole)","price":"$68"},{"dish":"Soup Dumplings","price":"$14"},{"dish":"Crispy Prawns with Walnuts","price":"$32"}]'::jsonb,
  'Manager', null, '(212) 956-6888'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('tang-pavilion', 'Banquet Room', 60, 0, 'Round-table banquet setup — call to confirm');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'waterbar-sf', 'Waterbar', '399 The Embarcadero, San Francisco, CA 94105', 'San Francisco', 'sf',
  37.7902, -122.3887, 'Seafood', 'Floor-to-ceiling aquarium columns and Bay Bridge views; private rooms open onto the Embarcadero.',
  4.2, 2874, 3, 4000,
  'verified', 'verified', '{"vegetarian","gluten_free","nut_allergy"}', '{"seated","reception"}',
  'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=900&q=60', 'https://www.waterbarsf.com/', null, '[{"dish":"Iced Shellfish Platter","price":"$95"},{"dish":"Grilled Whole Branzino","price":"$44"},{"dish":"Oysters (daily rotation)","price":"$4/ea"}]'::jsonb,
  'Events Director', 'events@waterbarsf.com', '(415) 284-9922'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('waterbar-sf', 'Terrace Room', 48, 60, 'Bridge views, opens to terrace');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('waterbar-sf', 'Chart Room', 24, 30, 'Board-style with AV');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'epic-steak-sf', 'EPIC Steak', '369 The Embarcadero, San Francisco, CA 94105', 'San Francisco', 'sf',
  37.7899, -122.3891, 'Steakhouse', 'Waterfront steakhouse with fire-pit terrace directly under the Bay Bridge lights.',
  4.2, 2310, 4, 6000,
  'verified', 'verified', '{"vegetarian","gluten_free","nut_allergy"}', '{"seated","reception"}',
  'https://images.unsplash.com/photo-1544025162-d76694265947?w=900&q=60', 'https://www.epicsteak.com/', null, '[{"dish":"Wood-Grilled Ribeye","price":"$74"},{"dish":"Dungeness Crab Cake","price":"$28"},{"dish":"S''mores Baked Alaska","price":"$18"}]'::jsonb,
  'Private Dining Manager', 'events@epicsteak.com', '(415) 369-9955'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('epic-steak-sf', 'Quiver Room', 80, 120, 'Glass walls on the water');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('epic-steak-sf', 'Fire Terrace', 40, 80, 'Heated outdoor reception space');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'boulevard-sf', 'Boulevard', '1 Mission St, San Francisco, CA 94105', 'San Francisco', 'sf',
  37.7935, -122.3927, 'American', 'James Beard-winning Belle Époque dining room in the 1889 Audiffred Building on the Embarcadero.',
  4.4, 3105, 4, 5500,
  'verified', 'verified', '{"vegetarian","gluten_free","nut_allergy"}', '{"seated"}',
  'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=900&q=60', 'https://www.boulevardrestaurant.com/', null, '[{"dish":"Wood-Oven Roasted Duck","price":"$52"},{"dish":"Prime Filet with Bone Marrow","price":"$68"},{"dish":"Butterscotch Pot de Crème","price":"$16"}]'::jsonb,
  'Events Coordinator', 'events@boulevardrestaurant.com', '(415) 543-6084'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('boulevard-sf', 'The Loft', 36, 45, 'Elevated room above the kitchen');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('boulevard-sf', 'Bay View Room', 60, 70, 'Windows on the Embarcadero');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'one-market-sf', 'One Market Restaurant', '1 Market St, San Francisco, CA 94105', 'San Francisco', 'sf',
  37.7938, -122.3946, 'American', 'High-ceilinged farm-to-table landmark facing the Ferry Building with a full private-dining wing.',
  4.1, 1980, 3, 4500,
  'verified', 'verified', '{"vegetarian","vegan","gluten_free","nut_allergy"}', '{"seated","reception"}',
  'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=900&q=60', 'https://www.onemarket.com/', null, '[{"dish":"Mission Fig & Burrata","price":"$24"},{"dish":"Slow-Roasted Salmon","price":"$42"},{"dish":"Butterscotch Pudding","price":"$14"}]'::jsonb,
  'Director of Events', 'events@onemarket.com', '(415) 777-5577'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('one-market-sf', 'Vintners Room', 70, 90, 'Largest private room');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('one-market-sf', 'Prosperity Room', 24, 30, 'AV-equipped boardroom feel');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('one-market-sf', 'Full Buyout', 170, 220, 'Entire restaurant, evenings');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'perbacco-sf', 'Perbacco', '230 California St, San Francisco, CA 94111', 'San Francisco', 'sf',
  37.7935, -122.399, 'Italian', 'Piemontese fine dining on California Street — house-made agnolotti and a serious Barolo list.',
  4.4, 2422, 3, 3500,
  'verified', 'verified', '{"vegetarian","gluten_free","nut_allergy"}', '{"seated"}',
  'https://images.unsplash.com/photo-1481931098730-318b6f776db0?w=900&q=60', 'https://www.perbaccosf.com/', null, '[{"dish":"Agnolotti dal Plin","price":"$29"},{"dish":"Braised Short Rib","price":"$46"},{"dish":"Bunet al Cioccolato","price":"$13"}]'::jsonb,
  'Events Manager', 'events@perbaccosf.com', '(415) 955-0663'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('perbacco-sf', 'Mezzanine', 40, 50, 'Overlooks the marble bar');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('perbacco-sf', 'Salumi Room', 14, 0, 'Chef''s-table intimacy');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'tadich-grill', 'Tadich Grill', '240 California St, San Francisco, CA 94111', 'San Francisco', 'sf',
  37.7936, -122.3993, 'Seafood', 'California''s oldest restaurant (1849) — cioppino, sourdough, and wood-panelled booths.',
  4.2, 3540, 3, null,
  'unverified', 'unverified', '{"gluten_free"}', '{"seated"}',
  'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=60', 'https://www.tadichgrillsf.com/', null, '[{"dish":"Cioppino","price":"$48"},{"dish":"Petrale Sole Doré","price":"$39"},{"dish":"Hangtown Fry","price":"$28"}]'::jsonb,
  'Front of House', null, '(415) 391-1849'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('tadich-grill', 'Back Room', 24, 0, 'No formal events program — call to confirm');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'kokkari-sf', 'Kokkari Estiatorio', '200 Jackson St, San Francisco, CA 94111', 'San Francisco', 'sf',
  37.7969, -122.3993, 'Greek', 'Rustic-luxe Aegean taverna with a roaring hearth — one of SF''s most requested private rooms.',
  4.6, 4870, 3, 6000,
  'verified', 'verified', '{"vegetarian","gluten_free","nut_allergy"}', '{"seated","reception"}',
  'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=900&q=60', 'https://kokkari.com/', null, '[{"dish":"Whole Grilled Branzino","price":"$46"},{"dish":"Moussaka","price":"$34"},{"dish":"Lamb Chops Riganato","price":"$58"}]'::jsonb,
  'Private Dining', 'events@kokkari.com', '(415) 981-0983'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('kokkari-sf', 'Private Dining Room', 40, 50, 'Fireplace and rotisserie view');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('kokkari-sf', 'Taverna Buyout', 70, 120, 'Front room, evenings only');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'yank-sing-sf', 'Yank Sing', '101 Spear St, San Francisco, CA 94105', 'San Francisco', 'sf',
  37.7917, -122.393, 'Chinese', 'Two-generation dim sum institution in Rincon Center with cart service and banquet rooms.',
  4.1, 5230, 2, 2500,
  'verified', 'verified', '{"vegetarian","vegan","gluten_free","nut_allergy"}', '{"seated","reception"}',
  'https://images.unsplash.com/photo-1526318896980-cf78c088247c?w=900&q=60', 'https://www.yanksing.com/', null, '[{"dish":"Shanghai Soup Dumplings","price":"$12"},{"dish":"Peking Duck by the Slice","price":"$9"},{"dish":"Banquet Menus","price":"from $58/pp"}]'::jsonb,
  'Banquet Sales', 'info@yanksing.com', '(415) 781-1111'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('yank-sing-sf', 'Atrium Room', 100, 140, 'Rincon Center atrium overflow');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('yank-sing-sf', 'Spear Room', 40, 0, 'Round tables, lazy susans');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'harborview-sf', 'Harborview Restaurant & Bar', '4 Embarcadero Center, San Francisco, CA 94111', 'San Francisco', 'sf',
  37.795, -122.3957, 'Chinese', 'Hong Kong-style banquet house with bay views — built for weddings, galas, and 300-person receptions.',
  4, 1450, 2, 3800,
  'verified', 'verified', '{"vegetarian","vegan","gluten_free","nut_allergy"}', '{"seated","reception"}',
  'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=900&q=60', 'https://www.harborviewsf.com/', null, '[{"dish":"Roast Suckling Pig","price":"$128"},{"dish":"Honey-Walnut Prawns","price":"$34"},{"dish":"Banquet Set Menus","price":"from $68/pp"}]'::jsonb,
  'Banquet Director', 'events@harborviewsf.com', '(415) 781-8833'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('harborview-sf', 'Grand Bay Room', 200, 300, 'Full banquet hall, bay windows');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('harborview-sf', 'Jade Room', 30, 40, 'Private round-table room');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'la-mar-sf', 'La Mar Cocina Peruana', 'Pier 1.5 The Embarcadero, San Francisco, CA 94111', 'San Francisco', 'sf',
  37.7973, -122.3948, 'Peruvian', 'Gastón Acurio''s cebichería on the pier — pisco bar and a terrace straight over the water.',
  4.2, 3120, 3, null,
  'likely', 'likely', '{"vegetarian","vegan","gluten_free"}', '{"seated","reception"}',
  'https://images.unsplash.com/photo-1559847844-5315695dadae?w=900&q=60', 'https://lamarsf.com/', null, '[{"dish":"Cebiche Clásico","price":"$26"},{"dish":"Arroz con Mariscos","price":"$38"},{"dish":"Pisco Sour","price":"$16"}]'::jsonb,
  'Events Team', 'eventossf@lamarcebicheria.com', '(415) 397-8880'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('la-mar-sf', 'Salón Miraflores', 40, 60, 'Private room, pier views');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('la-mar-sf', 'Terraza', 80, 120, 'Covered outdoor reception');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'ozumo-sf', 'Ozumo', '161 Steuart St, San Francisco, CA 94105', 'San Francisco', 'sf',
  37.7916, -122.3914, 'Japanese', 'Contemporary izakaya and robata grill with a sake lounge that hosts standing receptions.',
  4, 2680, 3, null,
  'likely', 'likely', '{"vegetarian","gluten_free","nut_allergy"}', '{"seated","reception"}',
  'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=900&q=60', 'https://ozumosanfrancisco.com/', null, '[{"dish":"Robata Black Cod","price":"$42"},{"dish":"Omakase Sushi Platter","price":"$85"},{"dish":"Sake Flights","price":"$28"}]'::jsonb,
  'Events Sales', 'sfevents@ozumo.com', '(415) 882-1333'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('ozumo-sf', 'Sake Lounge', 60, 100, 'Semi-private lounge takeover');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('ozumo-sf', 'Tatami Room', 16, 0, 'Traditional low-table room');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'fogo-de-chao-sf', 'Fogo de Chão', '201 3rd St, San Francisco, CA 94103', 'San Francisco', 'sf',
  37.7847, -122.4, 'Brazilian', 'Churrasco spit-roast service that scales effortlessly — gaucho chefs carve tableside all night.',
  4.3, 2905, 3, 3000,
  'verified', 'verified', '{"vegetarian","gluten_free","nut_allergy"}', '{"seated","reception"}',
  'https://images.unsplash.com/photo-1558030006-450675393462?w=900&q=60', 'https://fogodechao.com/', null, '[{"dish":"Full Churrasco Experience","price":"$64/pp"},{"dish":"Market Table & Feijoada Bar","price":"$34/pp"},{"dish":"Picanha (signature cut)","price":"—"}]'::jsonb,
  'Group Sales', 'sanfrancisco@fogo.com', '(415) 431-3364'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('fogo-de-chao-sf', 'Gaucho Room', 100, 140, 'Divisible private room');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('fogo-de-chao-sf', 'Wine Wall Room', 30, 40, 'Glass wine display walls');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'osha-thai-embarcadero', 'Osha Thai Embarcadero', '4 Embarcadero Center, San Francisco, CA 94111', 'San Francisco', 'sf',
  37.7952, -122.396, 'Thai', 'Sleek modern Thai in Embarcadero Center — lounge seating groups without full privacy.',
  3.9, 2100, 2, null,
  'unverified', 'unverified', '{"vegetarian","vegan","gluten_free","nut_allergy"}', '{"seated"}',
  'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=900&q=60', 'https://www.oshathai.com/', null, '[{"dish":"Volcanic Beef","price":"$32"},{"dish":"Pad Thai with Prawns","price":"$24"},{"dish":"Tom Yum Whole Fish","price":"$38"}]'::jsonb,
  'Manager', null, '(415) 788-6742'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('osha-thai-embarcadero', 'Lounge Section', 40, 60, 'Semi-private — call to confirm');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'tropics-hhv', 'Tropics Bar & Grill', '2005 Kalia Rd, Honolulu, HI 96815', 'Honolulu', 'waikiki',
  21.2837, -157.8385, 'American', 'Toes-in-the-sand beachfront bar inside Hilton Hawaiian Village — the house venue for lawn receptions.',
  4, 3320, 2, 5000,
  'verified', 'verified', '{"vegetarian","vegan","gluten_free","nut_allergy","kosher"}', '{"reception","seated"}',
  'https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?w=900&q=60', 'https://www.hiltonhawaiianvillage.com/', null, '[{"dish":"Kalua Pork Sliders","price":"$22"},{"dish":"Ahi Poke Bowl","price":"$26"},{"dish":"Tropical Pupu Platters","price":"from $45"}]'::jsonb,
  'HHV Events & Catering', 'hhvevents@hilton.com', '(808) 949-4321'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('tropics-hhv', 'Beachfront Buyout', 180, 300, 'Full venue with lawn extension');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('tropics-hhv', 'Lanai', 60, 90, 'Covered oceanfront section');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'bali-oceanfront-hhv', 'Bali Oceanfront', '2005 Kalia Rd, Honolulu, HI 96815', 'Honolulu', 'waikiki',
  21.2839, -157.8382, 'Seafood', 'Hilton Hawaiian Village''s signature oceanfront dining room — steak, seafood, and sunset views.',
  4.2, 1240, 4, 8000,
  'verified', 'verified', '{"vegetarian","vegan","gluten_free","nut_allergy","kosher"}', '{"seated","reception"}',
  'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=900&q=60', 'https://www.hiltonhawaiianvillage.com/', null, '[{"dish":"Whole Kona Lobster","price":"$88"},{"dish":"Miso Butterfish","price":"$54"},{"dish":"Wagyu Striploin","price":"$92"}]'::jsonb,
  'HHV Events & Catering', 'hhvevents@hilton.com', '(808) 949-4321'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('bali-oceanfront-hhv', 'Private Dining Room', 40, 50, 'Ocean-facing glass room');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('bali-oceanfront-hhv', 'Full Restaurant Buyout', 120, 180, 'Evenings, subject to season');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  '100-sails', '100 Sails Restaurant & Bar', '100 Holomoana St, Honolulu, HI 96815', 'Honolulu', 'waikiki',
  21.2866, -157.842, 'Seafood', 'Prince Waikiki''s marina-view dining room — island buffets and one of Waikiki''s largest event floors.',
  4.2, 2150, 3, 6000,
  'verified', 'verified', '{"vegetarian","vegan","gluten_free","nut_allergy","kosher"}', '{"reception","seated"}',
  'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=900&q=60', 'https://www.100sails.com/', null, '[{"dish":"Crab Leg & Prime Rib Buffet","price":"$98/pp"},{"dish":"Poke & Raw Bar Station","price":"—"},{"dish":"Reception Packages","price":"from $75/pp"}]'::jsonb,
  'Prince Waikiki Catering', 'catering@princewaikiki.com', '(808) 944-4494'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('100-sails', 'Promenade Room', 80, 120, 'Marina-view private room');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('100-sails', 'Full Venue Reception', 200, 350, 'Entire restaurant floor');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'monkeypod-waikiki', 'Monkeypod Kitchen by Merriman', '2169 Kalia Rd, Honolulu, HI 96815', 'Honolulu', 'waikiki',
  21.279, -157.832, 'Hawaiian', 'Peter Merriman''s farm-to-table beach house at Outrigger Reef — mai tais with lilikoi foam, live music daily.',
  4.3, 4310, 2, 4000,
  'verified', 'verified', '{"vegetarian","vegan","gluten_free","nut_allergy"}', '{"reception","seated"}',
  'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=900&q=60', 'https://monkeypodkitchen.com/', null, '[{"dish":"Saimin Noodles & Pork Belly","price":"$24"},{"dish":"Wood-Fired Pizzas","price":"$21"},{"dish":"Famous Mai Tai","price":"$17"}]'::jsonb,
  'Events Coordinator', 'waikikievents@monkeypodkitchen.com', '(808) 900-4226'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('monkeypod-waikiki', 'Oceanfront Lanai', 50, 80, 'Covered, ocean rail seating');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('monkeypod-waikiki', 'Full Buyout', 180, 280, 'Both floors, evenings');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'rum-fire-waikiki', 'Rum Fire', '2255 Kalakaua Ave, Honolulu, HI 96815', 'Honolulu', 'waikiki',
  21.2769, -157.8291, 'Hawaiian', 'Sheraton Waikiki''s fire-pit lounge on the sand — built for sunset happy hours at scale.',
  4, 1980, 2, null,
  'likely', 'likely', '{"vegetarian","gluten_free"}', '{"reception"}',
  'https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?w=900&q=60', 'https://www.rumfirewaikiki.com/', null, '[{"dish":"Kalbi Short Rib Tacos","price":"$23"},{"dish":"Spicy Garlic Edamame","price":"$14"},{"dish":"Rum Flight","price":"$32"}]'::jsonb,
  'Sheraton Waikiki Events', null, '(808) 922-4422'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('rum-fire-waikiki', 'Lounge Takeover', 150, 250, 'Oceanfront fire-pit terraces');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'dukes-waikiki', 'Duke''s Waikiki', '2335 Kalakaua Ave, Honolulu, HI 96815', 'Honolulu', 'waikiki',
  21.2766, -157.8262, 'American', 'Barefoot-luxe beachfront legend honoring Duke Kahanamoku — hula pie is mandatory.',
  4.2, 7120, 2, 3000,
  'verified', 'verified', '{"vegetarian","gluten_free","nut_allergy"}', '{"seated","reception"}',
  'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=60', 'https://www.dukeswaikiki.com/', null, '[{"dish":"Huli Huli Chicken","price":"$34"},{"dish":"Fresh Catch, Parmesan Crusted","price":"$44"},{"dish":"Hula Pie","price":"$14"}]'::jsonb,
  'Banquet Manager', 'dukesbanquets@tsrestaurants.com', '(808) 922-2268'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('dukes-waikiki', 'Canoe Club Room', 60, 100, 'Private upstairs room');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'hula-grill-waikiki', 'Hula Grill Waikiki', '2335 Kalakaua Ave, Honolulu, HI 96815', 'Honolulu', 'waikiki',
  21.2766, -157.8262, 'Hawaiian', 'Plantation-house dining room above Duke''s with panoramic Diamond Head views.',
  4.3, 3540, 2, null,
  'unverified', 'likely', '{"vegetarian","vegan","gluten_free"}', '{"seated"}',
  'https://images.unsplash.com/photo-1559847844-5315695dadae?w=900&q=60', 'https://www.hulagrillwaikiki.com/', null, '[{"dish":"Macadamia Nut Crusted Mahi","price":"$42"},{"dish":"Pineapple Fried Rice","price":"$26"},{"dish":"Kimo''s Original Hula Pie","price":"$14"}]'::jsonb,
  'Group Dining', null, '(808) 923-4852'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('hula-grill-waikiki', 'Ocean Lanai', 40, 60, 'Semi-private veranda section');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'wolfgangs-waikiki', 'Wolfgang''s Steakhouse Waikiki', '2301 Kalakaua Ave, Honolulu, HI 96815', 'Honolulu', 'waikiki',
  21.2778, -157.8272, 'Steakhouse', 'Peter Luger-lineage dry-aged porterhouse in the Royal Hawaiian Center, with clubby private rooms.',
  4.1, 2870, 4, 7000,
  'likely', 'verified', '{"vegetarian","gluten_free","nut_allergy"}', '{"seated","reception"}',
  'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=900&q=60', 'https://wolfgangssteakhouse.net/', null, '[{"dish":"Porterhouse for Four","price":"$260"},{"dish":"Jumbo Shrimp Cocktail","price":"$29"},{"dish":"German Potatoes","price":"$16"}]'::jsonb,
  'Private Events', 'waikiki@wolfgangssteakhouse.net', '(808) 922-3600'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('wolfgangs-waikiki', 'Boardroom', 40, 0, 'Wine-wall private room');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('wolfgangs-waikiki', 'Terrace Buyout', 80, 120, 'Open-air section over Kalakaua');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'roys-waikiki', 'Roy''s Waikiki', '226 Lewers St, Honolulu, HI 96815', 'Honolulu', 'waikiki',
  21.2787, -157.829, 'Hawaiian', 'Roy Yamaguchi''s flagship Hawaiian-fusion kitchen — misoyaki butterfish and melting hot chocolate soufflé.',
  4.4, 4980, 3, 4500,
  'verified', 'verified', '{"vegetarian","vegan","gluten_free","nut_allergy"}', '{"seated"}',
  'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=900&q=60', 'https://www.royyamaguchi.com/roys-waikiki', null, '[{"dish":"Misoyaki Butterfish","price":"$52"},{"dish":"Braised Short Ribs","price":"$49"},{"dish":"Melting Hot Chocolate Soufflé","price":"$16"}]'::jsonb,
  'Events Coordinator', 'waikikievents@roysrestaurant.com', '(808) 923-7697'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('roys-waikiki', 'Private Dining Room', 24, 0, 'Glass-walled wine room');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('roys-waikiki', 'Lanai Section', 60, 80, 'Semi-private covered patio');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'morimoto-asia-waikiki', 'Morimoto Asia Waikiki', '2490 Kalakaua Ave, Honolulu, HI 96815', 'Honolulu', 'waikiki',
  21.2712, -157.8222, 'Japanese', 'Iron Chef Morimoto''s pan-Asian hall at the Alohilani — sushi, Peking duck, and ocean-view terraces.',
  4.2, 2230, 3, 5000,
  'verified', 'verified', '{"vegetarian","vegan","gluten_free","nut_allergy","kosher"}', '{"seated","reception"}',
  'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=900&q=60', 'https://www.alohilaniresort.com/dining/morimoto-asia-waikiki/', null, '[{"dish":"Morimoto Peking Duck","price":"$88"},{"dish":"Ishiyaki Buri Bop","price":"$46"},{"dish":"Omakase Sushi","price":"from $95"}]'::jsonb,
  'Alohilani Events', 'events@alohilaniresort.com', '(808) 922-0022'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('morimoto-asia-waikiki', 'Private Dining Room', 30, 40, 'Sliding-screen room');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('morimoto-asia-waikiki', 'Terrace Reception', 120, 200, 'Ocean-view terrace takeover');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'herringbone-waikiki', 'Herringbone Waikiki', '2330 Kalakaua Ave, Honolulu, HI 96815', 'Honolulu', 'waikiki',
  21.2772, -157.8253, 'Seafood', 'Open-air ''ocean-to-table'' loft in International Market Place under a century-old banyan tree.',
  4.2, 1870, 3, null,
  'likely', 'likely', '{"vegetarian","gluten_free","nut_allergy"}', '{"reception","seated"}',
  'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=900&q=60', 'https://www.herringboneeats.com/', null, '[{"dish":"Whole Roasted Fish","price":"$52"},{"dish":"Oyster Hour Selection","price":"$3.50/ea"},{"dish":"Lobster Roll","price":"$36"}]'::jsonb,
  'Events Team', 'eventswaikiki@herringboneeats.com', '(808) 797-2435'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('herringbone-waikiki', 'Sunroom', 40, 60, 'Glass-wrapped private corner');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('herringbone-waikiki', 'Full Venue', 150, 250, 'Complete open-air buyout');

insert into public.venues (id, name, address, city, region, lat, lng, cuisine, description, rating, review_count, price_tier, min_spend, price_trust, trust_label, dietary, event_styles, image_url, menu_url, menu_image_url, menu_highlights, contact_name, contact_email, contact_phone) values (
  'pf-changs-waikiki', 'P.F. Chang''s Waikiki', '2201 Kalakaua Ave, Honolulu, HI 96815', 'Honolulu', 'waikiki',
  21.2786, -157.8296, 'Chinese', 'Two-story wok house at Royal Hawaiian Center with lantern-lit balcony over Kalakaua.',
  3.8, 2440, 2, null,
  'likely', 'likely', '{"vegetarian","vegan","gluten_free","nut_allergy"}', '{"seated","reception"}',
  'https://images.unsplash.com/photo-1526318896980-cf78c088247c?w=900&q=60', 'https://www.pfchangs.com/', null, '[{"dish":"Chang''s Lettuce Wraps","price":"$16"},{"dish":"Mongolian Beef","price":"$28"},{"dish":"Great Wall of Chocolate","price":"$13"}]'::jsonb,
  'Banquet Line', null, '(808) 628-6760'
);
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('pf-changs-waikiki', 'Balcony Room', 40, 60, 'Private upstairs room');
insert into public.private_rooms (venue_id, name, seated_capacity, standing_capacity, notes) values ('pf-changs-waikiki', 'Main Floor Section', 100, 140, 'Semi-private partition');

